### PR TITLE
removed error_log output to stderr because docker bug in old releases

### PR DESCRIPTION
**Pull request by jmprusi**
related to https://github.com/3scale/docker-gateway/issues/69

### CODE REVIEW

**Comment by mikz** [comment]
I'd not say it closes the issue, because it will still remain in v2. 
And there, to fix it properly we should try to write to the logs and if it does not succeed symlink them to dev null.

**Comment by jmprusi** [comment]
Do you plan on support old docker version in v2?

**Comment by mikz** [comment]
I don't know yet. Something to decide.

**Comment by jayenashar** [comment]
sorry i don't think this is related to #69.  #69 is about using `/dev/stdout` as a file, not about using stderr as a file descriptor.  error_log with stderr works fine.  it's access_log (which doesn't support stdout/stderr) that doesn't work because `/dev/stdout` gives `permission denied`

**Comment by jmprusi** [comment]
@jayenashar I see the issue, we removed the access_log.. but we didn't update the docker image, sorry about that.

Can you try building the image from this repo, and running it? 

I will update the docker image in the quay repo with the latest code.

**Comment by jmprusi** [comment]
I will close this PR, and open another adding access_log again but with the simple fallback method.

**Pull request closed without merging**
